backend:
  name: git-gateway

media_folder: "site/static/media" # Folder where user uploaded files should go
public_folder: "media"

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "site/content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "text", default: "Quang Luong"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Weight", name: "weight", widget: "number", default: 10}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Enable Disqus", name: "enableDisqus", widget: "boolean", default: true}
      - {label: "Enable Share", name: "enableShare", widget: "boolean", default: true}
      - {label: "Body", name: "body", widget: "markdown"}
